//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pathfinder.Test.Serializers.Json.CharacterTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pathfinder.Test.Serializers.Json.CharacterTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Age&quot;: 10,
        ///	&quot;Alignment&quot;: &quot;lawfulGood&quot;,
        ///	&quot;Deity&quot;: {
        ///		&quot;Name&quot;: &quot;Deity&quot;
        ///	},
        ///	&quot;Gender&quot;: &quot;male&quot;,
        ///	&quot;Eyes&quot;: &quot;Blue&quot;,
        ///	&quot;Hair&quot;: &quot;Blue&quot;,
        ///	&quot;Height&quot;: &quot;9&apos; 6\&quot;&quot;,
        ///	&quot;Weight&quot;: &quot;180 lbs.&quot;,
        ///	&quot;Homeland&quot;: &quot;Homeland&quot;,
        ///	&quot;Name&quot;: &quot;Unit McTesterFace&quot;,
        ///	&quot;Race&quot;: &quot;Test Race&quot;,
        ///	&quot;BaseSize&quot;: &quot;medium&quot;,
        ///	&quot;Size&quot;: &quot;medium&quot;,
        ///	&quot;Languages&quot;: [
        ///		&quot;Test Language&quot;,
        ///		&quot;Mock Language&quot;
        ///	],
        ///	&quot;MaxHealthPoints&quot;: 7,
        ///	&quot;Damage&quot;: 2,
        ///	&quot;HealthPoints&quot;: 5,
        ///	&quot;BaseSpeed&quot;: 30,
        ///	&quot;Speed&quot;: 25,
        ///	&quot;Purse&quot;: {
        ///		&quot;Copper&quot;: 1,
        ///		&quot;Silver&quot;: 2,
        ///		&quot;G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacter {
            get {
                return ResourceManager.GetString("TestCharacter", resourceCulture);
            }
        }
    }
}
